#!/bin/sh

PREREQ=""
DESCRIPTION="Disabling cosmic-initial-setup..."

prereqs()
{
       echo "$PREREQ"
}

case $1 in
# get pre-requisites
prereqs)
       prereqs
       exit 0
       ;;
esac

. /scripts/casper-functions

log_begin_msg "$DESCRIPTION"

rm -f /root/etc/xdg/autostart/com.system76.CosmicInitialSetup.desktop

log_end_msg
